### ISSUE TITLE
[bug] 脚本 onResponse 内添加任意代码 报错

### ISSUE THREAD

**Issue by cuinima** [reqable/reqable-app#826]
`# API Docs: https://reqable.com/docs/capture/addons

from reqable import *

def onResponse(context, response):
  # 打印请求信息，更多API请参考上文`CaptureHttpRequest`
  print(response.code)
  # 打印响应状态码，例如：200
  # Done
  return response
`
23:45:10.217 Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 12, in main
    onRequest(argv[1])
  File "main.py", line 22, in onRequest
    result = addons.onRequest(context, CaptureHttpRequest(data['request']))
AttributeError: module 'addons' has no attribute 'onRequest'

**Comment by cuinima** [comment]
找到原因了 必须要写上 onRequest 不能单独运行onResponse
def onRequest(context, request):
  return request
